title: REmatch - AI
description: Supporting drug discovery through image-based profiling
sitename: REmatch - AI
baseurl: ''
sass:
  sass_dir: /assets/_sass
  style: :compressed
collections:
  - features
twitter_username_cs:     chri_sche
twitter_username_fh:     FlorianHeigwer
google_username_fh:      QEUKuFMAAAAJ
linkedin_username_fh:     florian-heigwer
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.txt
  - CNAME