title: REmatch - AI
description: Supporting drug discovery through image-based profiling
sitename: REmatch - AI
baseurl: ''
sass:
  sass_dir: /assets/_sass
  style: :compressed
collections:
  - features
twitter_username:     chri_sche
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.txt
  - CNAME