title: Rematch-AI
description: Supporting drug discovery through image-based profiling
sitename: Rematch-AI
baseurl: ''
sass:
  sass_dir: /assets/_sass
  style: :compressed
collections:
  - features
twitter_username_cs:     chri_sche
twitter_username_mb:     Boutroslab
twitter_username_fh:     FlorianHeigwer
google_username_fh:      QEUKuFMAAAAJ
google_username_mb:      k-q8lsYAAAAJ&hl
linkedin_username_fh:    florian-heigwer-258a5ba6
linkedin_username_tm:    thilo-miersch-b6642484
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.txt
  - CNAME