title: REmatch - AI
description: Accelerating drug discovery through image profiling
sitename: rematch.ai
baseurl: 'https://rematch-ai.github.io/'
sass:
  sass_dir: /assets/_sass
  style: :compressed
collections:
  - features
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.txt
  - CNAME